blank_issues_enabled: true
contact_links:
  - name: Discord Chat
    url: https://discord.com/channels/1212897693450641498/1230231823674642513
    about: Ask questions and discuss with other Lilypad RPs and users in real time.
    ---
**Don't see your issue?** [Open a blank issue here](https://github.com/your-username/your-repo/issues/new).

